name: Deploy to Amplify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli@4.11.0

      - name: Configure Amplify
        run: amplify configure

      - name: Deploy to Amplify
        run: amplify publish
